<?php

/*
 *
 *      █████╗ ███████╗████████╗██╗  ██╗███████╗██████╗         ██████╗ ██╗  ██╗██████╗
 *     ██╔══██╗██╔════╝╚══██╔══╝██║  ██║██╔════╝██╔══██╗        ██╔══██╗██║  ██║██╔══██╗
 *     ███████║█████╗     ██║   ███████║█████╗  ██████╔╝ █████╗ ██████╔╝███████║██████╔╝
 *     ██╔══██║██╔══╝     ██║   ██╔══██║██╔══╝  ██╔══██╗ ╚════╝ ██╔═══╝ ██╔══██║██╔═══╝
 *     ██║  ██║███████╗   ██║   ██║  ██║███████╗██║  ██║        ██║     ██║  ██║██║
 *     ╚═╝  ╚═╝╚══════╝   ╚═╝   ╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝        ╚═╝     ╚═╝  ╚═╝╚═╝
 *
 *                  The divine secure, lightweight PHP framework
 *                   < 1 Mo • Zero dependencies • Pure PHP 8.3+
 *
 *  Built from scratch. No bloat. OOP Embedded.
 *
 *  @author: dawnl3ss (Alex') ©2026 — All rights reserved
 *  Source available • Commercial license required for redistribution
 *  → https://aetherphp.net
 *  → https://github.com/Aether-PHP/Aether-PHP
 *
*/
declare(strict_types=1);

namespace Aether\Auth\User;


interface UserInterface {

    /**
     * Get User's UID : an INT auto-generated by the DB table.
     *
     * @return int
     */
    public function _getUid() : int;

    /**
     * Get User's username
     *
     * @return string
     */
    public function _getUsername() : string;

    /**
     * Get User's email
     *
     * @return string
     */
    public function _getEmail() : string;


    /**
     * Check User's permissions : used for admin check-ups and user backend-related operations
     *
     * @param mixed $_perm
     *
     * @return bool
     */
    public function _hasPerm(mixed $_perm) : bool;

    /**
     * Add permission to a User
     *
     * @param mixed $_perm
     *
     * @return UserInstance
     */
    public function _addPerm(mixed $_perm) : UserInstance;


    /**
     * Remove permission to a User
     *
     * @param mixed $_perm
     *
     * @return UserInstance
     */
    public function _removePerm(mixed $_perm) : UserInstance;

    /**
     * Get User's permissions : used for admin check-ups and user backend-related operations
     *
     * @return array
     */
    public function _getPerms() : array;

    /**
     * Check if User is admin
     *
     * @return bool
     */
    public function _isAdmin() : bool;

}